input_max_length: 32768,65536,131072
datasets: json_kv_chinese_poem,json_kv_chinese_poem,json_kv_chinese_poem
generation_max_length: 100,100,100
test_files: data/chinese-poetry/tang_poetry_kv_test_32k.jsonl,data/chinese-poetry/tang_poetry_kv_test_64k.jsonl,data/chinese-poetry/tang_poetry_kv_test_128k.jsonl
demo_files: ',,'
use_chat_template: false
max_test_samples: 100
shots: 2
stop_new_line: false
model_name_or_path: self-define
